services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=gconnect
    ports:
      - "5432:5432"
    volumes:
      - gconnect-db:/var/lib/postgresql/data
    restart: always

volumes:
  gconnect-db:
    driver: local